# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - portfolio-website

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: npm install, build, and test
        run: |
          npm install
          npm run azure
          npm run test --if-present
        env:
          CONNECTION_URL: mongodb://portfolio-website:w2HYeBImnpRcZqIe6jWa6IaJqY6MP3R8QLwPctZPhy6l9G6za0HF4LlUx9Bic5EiN9TI2FB49AsNBQIIQrL6mA==@portfolio-website.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@portfolio-website@
          DB_USER: portfolio-website
          DB_PASS: w2HYeBImnpRcZqIe6jWa6IaJqY6MP3R8QLwPctZPhy6l9G6za0HF4LlUx9Bic5EiN9TI2FB49AsNBQIIQrL6mA==
      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v1
        with:
          app-name: "portfolio-website"
          slot-name: "production"
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_0ae57e0bd60f48d6a6a86f115e778fb5 }}
          package: .
